import JSZip from "jszip";
import { BYOD_SCHEMA_VERSION } from "./version";
import { generateSchemaFile } from "./schemaGenerator";

/**
 * Generate a downloadable zip file with the BYOD project
 * for users who need to deploy manually
 */
export async function generateDownloadableProject(): Promise<Blob> {
	const zip = new JSZip();

	// Add package.json
	zip.file(
		"package.json",
		JSON.stringify(
			{
				name: "blah-chat-byod",
				version: "1.0.0",
				private: true,
				scripts: {
					dev: "npx convex dev",
					deploy: "npx convex deploy",
				},
				dependencies: {
					convex: "^1.17.0",
				},
			},
			null,
			2,
		),
	);

	// Add convex.json
	zip.file(
		"convex.json",
		JSON.stringify(
			{
				functions: "convex/",
			},
			null,
			2,
		),
	);

	// Add tsconfig.json
	zip.file(
		"tsconfig.json",
		JSON.stringify(
			{
				compilerOptions: {
					target: "ESNext",
					module: "ESNext",
					moduleResolution: "bundler",
					strict: true,
					skipLibCheck: true,
				},
				include: ["convex/**/*"],
			},
			null,
			2,
		),
	);

	// Add convex directory
	const convex = zip.folder("convex");

	// Add schema
	convex?.file("schema.ts", generateSchemaFile());

	// Add functions
	convex?.file("functions.ts", generateFunctionsContent());

	// Add README
	zip.file("README.md", generateReadme());

	// Add .gitignore
	zip.file(
		".gitignore",
		`node_modules/
.env
.env.local
`,
	);

	return await zip.generateAsync({ type: "blob" });
}

/**
 * Generate functions content for manual deployment
 */
function generateFunctionsContent(): string {
	return `// BYOD Functions v${BYOD_SCHEMA_VERSION}
// Auto-generated by blah.chat - DO NOT EDIT

import { query } from "./_generated/server";

// Health check - used to verify connection
export const ping = query({
  args: {},
  handler: async () => {
    return { status: "ok", version: ${BYOD_SCHEMA_VERSION}, timestamp: Date.now() };
  },
});

// System info - returns schema version
export const getSystemInfo = query({
  args: {},
  handler: async () => {
    return {
      schemaVersion: ${BYOD_SCHEMA_VERSION},
      provider: "blah.chat",
      type: "byod",
    };
  },
});
`;
}

/**
 * Generate README content
 */
function generateReadme(): string {
	return `# blah.chat BYOD Project

This is your personal blah.chat BYOD (Bring Your Own Database) project.
Schema version: ${BYOD_SCHEMA_VERSION}

## Prerequisites

- Node.js 18+
- A Convex account (https://convex.dev)

## Setup

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Link to your Convex project:
   \`\`\`bash
   npx convex dev
   \`\`\`
   Follow the prompts to create or link a project.

3. Deploy to production:
   \`\`\`bash
   npx convex deploy
   \`\`\`

4. Copy your deployment URL from the Convex dashboard.

5. Enter the deployment URL in blah.chat Settings > Database.

## Important Notes

- **DO NOT modify the schema** - blah.chat manages schema updates automatically.
- Your data is stored securely on your own Convex instance.
- blah.chat only stores your connection credentials (encrypted).

## Troubleshooting

### "Schema mismatch" error
Wait for blah.chat to deploy the latest schema, or re-download this project.

### "Connection failed" error
Verify your deployment URL is correct and your Convex project is active.

### Need help?
Contact support at support@blah.chat

---
Generated by blah.chat on ${new Date().toISOString()}
`;
}

/**
 * Trigger download of the BYOD project zip
 */
export async function downloadBYODProject(): Promise<void> {
	const blob = await generateDownloadableProject();

	// Create download link
	const url = URL.createObjectURL(blob);
	const a = document.createElement("a");
	a.href = url;
	a.download = `blah-chat-byod-v${BYOD_SCHEMA_VERSION}.zip`;
	document.body.appendChild(a);
	a.click();
	document.body.removeChild(a);
	URL.revokeObjectURL(url);
}
