import { BYOD_SCHEMA_VERSION } from "./version";

/**
 * Generates the schema.ts file content for deployment to user instances.
 * This creates a standalone schema file that can be deployed to a user's Convex project.
 */
export function generateSchemaFile(): string {
	return `// Auto-generated BYOD schema v${BYOD_SCHEMA_VERSION}
// DO NOT EDIT - This file is managed by blah.chat
// Generated at: ${new Date().toISOString()}

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // ===== Conversations =====
  conversations: defineTable({
    userId: v.string(),
    title: v.optional(v.string()),
    model: v.optional(v.string()),
    systemPrompt: v.optional(v.string()),
    isArchived: v.optional(v.boolean()),
    isPinned: v.optional(v.boolean()),
    lastMessageAt: v.optional(v.number()),
    messageCount: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_archived", ["userId", "isArchived"])
    .index("by_user_pinned", ["userId", "isPinned"])
    .index("by_user_last_message", ["userId", "lastMessageAt"])
    .searchIndex("search_title", {
      searchField: "title",
      filterFields: ["userId"],
    }),

  conversationParticipants: defineTable({
    conversationId: v.id("conversations"),
    clerkId: v.string(),
    role: v.union(v.literal("owner"), v.literal("collaborator"), v.literal("viewer")),
    joinedAt: v.number(),
  })
    .index("by_conversation", ["conversationId"])
    .index("by_user", ["clerkId"])
    .index("by_conversation_user", ["conversationId", "clerkId"]),

  // ===== Messages =====
  messages: defineTable({
    conversationId: v.id("conversations"),
    userId: v.string(),
    role: v.union(v.literal("user"), v.literal("assistant"), v.literal("system")),
    content: v.string(),
    model: v.optional(v.string()),
    status: v.optional(v.union(
      v.literal("pending"),
      v.literal("generating"),
      v.literal("complete"),
      v.literal("error"),
      v.literal("stopped")
    )),
    partialContent: v.optional(v.string()),
    error: v.optional(v.string()),
    generationStartedAt: v.optional(v.number()),
    generationCompletedAt: v.optional(v.number()),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    cost: v.optional(v.number()),
    parentMessageId: v.optional(v.id("messages")),
    branchIndex: v.optional(v.number()),
    embedding: v.optional(v.array(v.float64())),
    metadata: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_conversation", ["conversationId"])
    .index("by_conversation_created", ["conversationId", "createdAt"])
    .index("by_user", ["userId"])
    .index("by_parent", ["parentMessageId"])
    .index("by_status", ["status"])
    .searchIndex("search_content", {
      searchField: "content",
      filterFields: ["userId", "conversationId"],
    })
    .vectorIndex("embedding", {
      vectorField: "embedding",
      dimensions: 1536,
      filterFields: ["userId", "conversationId"],
    }),

  toolCalls: defineTable({
    messageId: v.id("messages"),
    toolName: v.string(),
    toolArgs: v.any(),
    result: v.optional(v.any()),
    status: v.union(v.literal("pending"), v.literal("complete"), v.literal("error")),
    error: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_message", ["messageId"]),

  sources: defineTable({
    messageId: v.id("messages"),
    url: v.string(),
    title: v.optional(v.string()),
    snippet: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_message", ["messageId"]),

  attachments: defineTable({
    messageId: v.id("messages"),
    userId: v.string(),
    storageId: v.optional(v.id("_storage")),
    filename: v.string(),
    mimeType: v.string(),
    size: v.number(),
    url: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_message", ["messageId"])
    .index("by_user", ["userId"]),

  // ===== Memories =====
  memories: defineTable({
    userId: v.string(),
    content: v.string(),
    category: v.optional(v.string()),
    source: v.optional(v.union(
      v.literal("extracted"),
      v.literal("manual"),
      v.literal("imported")
    )),
    sourceConversationId: v.optional(v.id("conversations")),
    sourceMessageId: v.optional(v.id("messages")),
    importance: v.optional(v.number()),
    embedding: v.optional(v.array(v.float64())),
    isActive: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_active", ["userId", "isActive"])
    .index("by_user_category", ["userId", "category"])
    .index("by_source_conversation", ["sourceConversationId"])
    .searchIndex("search_content", {
      searchField: "content",
      filterFields: ["userId", "category"],
    })
    .vectorIndex("embedding", {
      vectorField: "embedding",
      dimensions: 1536,
      filterFields: ["userId", "category", "isActive"],
    }),

  // ===== Files =====
  files: defineTable({
    userId: v.string(),
    storageId: v.optional(v.id("_storage")),
    filename: v.string(),
    mimeType: v.string(),
    size: v.number(),
    url: v.optional(v.string()),
    status: v.optional(v.union(
      v.literal("uploading"),
      v.literal("processing"),
      v.literal("ready"),
      v.literal("error")
    )),
    error: v.optional(v.string()),
    metadata: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_status", ["userId", "status"]),

  fileChunks: defineTable({
    fileId: v.id("files"),
    userId: v.string(),
    chunkIndex: v.number(),
    content: v.string(),
    embedding: v.optional(v.array(v.float64())),
    createdAt: v.number(),
  })
    .index("by_file", ["fileId"])
    .index("by_user", ["userId"])
    .vectorIndex("embedding", {
      vectorField: "embedding",
      dimensions: 1536,
      filterFields: ["userId", "fileId"],
    }),

  // ===== Projects =====
  projects: defineTable({
    userId: v.string(),
    name: v.string(),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    icon: v.optional(v.string()),
    isArchived: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_archived", ["userId", "isArchived"]),

  projectConversations: defineTable({
    projectId: v.id("projects"),
    conversationId: v.id("conversations"),
    addedAt: v.number(),
    addedBy: v.string(),
  })
    .index("by_project", ["projectId"])
    .index("by_conversation", ["conversationId"])
    .index("by_project_conversation", ["projectId", "conversationId"]),

  projectNotes: defineTable({
    projectId: v.id("projects"),
    noteId: v.id("notes"),
    addedAt: v.number(),
    addedBy: v.string(),
  })
    .index("by_project", ["projectId"])
    .index("by_note", ["noteId"]),

  projectFiles: defineTable({
    projectId: v.id("projects"),
    fileId: v.id("files"),
    addedAt: v.number(),
    addedBy: v.string(),
  })
    .index("by_project", ["projectId"])
    .index("by_file", ["fileId"]),

  // ===== Notes =====
  notes: defineTable({
    userId: v.string(),
    title: v.string(),
    content: v.string(),
    isPinned: v.optional(v.boolean()),
    isArchived: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_pinned", ["userId", "isPinned"])
    .index("by_user_archived", ["userId", "isArchived"])
    .searchIndex("search_content", {
      searchField: "content",
      filterFields: ["userId"],
    }),

  // ===== Tasks =====
  tasks: defineTable({
    userId: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    status: v.union(
      v.literal("todo"),
      v.literal("in_progress"),
      v.literal("done"),
      v.literal("cancelled")
    ),
    priority: v.optional(v.union(
      v.literal("low"),
      v.literal("medium"),
      v.literal("high"),
      v.literal("urgent")
    )),
    dueDate: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    sourceConversationId: v.optional(v.id("conversations")),
    sourceMessageId: v.optional(v.id("messages")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_status", ["userId", "status"])
    .index("by_user_due", ["userId", "dueDate"])
    .index("by_source_conversation", ["sourceConversationId"]),

  // ===== Bookmarks & Snippets =====
  bookmarks: defineTable({
    userId: v.string(),
    messageId: v.id("messages"),
    conversationId: v.id("conversations"),
    note: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_message", ["messageId"])
    .index("by_conversation", ["conversationId"]),

  snippets: defineTable({
    userId: v.string(),
    title: v.string(),
    content: v.string(),
    language: v.optional(v.string()),
    sourceMessageId: v.optional(v.id("messages")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_source", ["sourceMessageId"]),

  // ===== Tags =====
  tags: defineTable({
    userId: v.string(),
    name: v.string(),
    color: v.optional(v.string()),
    scope: v.union(v.literal("user"), v.literal("global")),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_name", ["name"]),

  conversationTags: defineTable({
    conversationId: v.id("conversations"),
    tagId: v.id("tags"),
    userId: v.string(),
    createdAt: v.number(),
  })
    .index("by_conversation", ["conversationId"])
    .index("by_tag", ["tagId"]),

  noteTags: defineTable({
    noteId: v.id("notes"),
    tagId: v.id("tags"),
    userId: v.string(),
    createdAt: v.number(),
  })
    .index("by_note", ["noteId"])
    .index("by_tag", ["tagId"]),

  taskTags: defineTable({
    taskId: v.id("tasks"),
    tagId: v.id("tags"),
    userId: v.string(),
    createdAt: v.number(),
  })
    .index("by_task", ["taskId"])
    .index("by_tag", ["tagId"]),

  // ===== Usage =====
  usageRecords: defineTable({
    userId: v.string(),
    date: v.string(),
    model: v.string(),
    inputTokens: v.number(),
    outputTokens: v.number(),
    cost: v.number(),
    requestCount: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_date", ["userId", "date"])
    .index("by_user_model", ["userId", "model"]),

  ttsCache: defineTable({
    hash: v.string(),
    storageId: v.id("_storage"),
    text: v.string(),
    voice: v.string(),
    createdAt: v.number(),
    expiresAt: v.number(),
  })
    .index("by_hash", ["hash"])
    .index("by_expires", ["expiresAt"]),

  // ===== Presentations =====
  presentations: defineTable({
    userId: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    theme: v.optional(v.string()),
    status: v.union(v.literal("draft"), v.literal("ready"), v.literal("presenting")),
    sourceConversationId: v.optional(v.id("conversations")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_status", ["userId", "status"]),

  slides: defineTable({
    presentationId: v.id("presentations"),
    userId: v.string(),
    order: v.number(),
    type: v.union(
      v.literal("title"),
      v.literal("content"),
      v.literal("image"),
      v.literal("code"),
      v.literal("split")
    ),
    content: v.any(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_presentation", ["presentationId"])
    .index("by_presentation_order", ["presentationId", "order"]),

  outlineItems: defineTable({
    presentationId: v.id("presentations"),
    userId: v.string(),
    order: v.number(),
    title: v.string(),
    content: v.optional(v.string()),
    isCompleted: v.optional(v.boolean()),
    createdAt: v.number(),
  }).index("by_presentation", ["presentationId"]),

  designTemplates: defineTable({
    userId: v.string(),
    name: v.string(),
    config: v.any(),
    isDefault: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_user", ["userId"]),

  presentationSessions: defineTable({
    presentationId: v.id("presentations"),
    userId: v.string(),
    currentSlide: v.number(),
    isActive: v.boolean(),
    startedAt: v.number(),
    endedAt: v.optional(v.number()),
  })
    .index("by_presentation", ["presentationId"])
    .index("by_user_active", ["userId", "isActive"]),

  // ===== Activity =====
  activityEvents: defineTable({
    userId: v.string(),
    type: v.string(),
    entityType: v.optional(v.string()),
    entityId: v.optional(v.string()),
    metadata: v.optional(v.any()),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_type", ["userId", "type"])
    .index("by_user_created", ["userId", "createdAt"]),
});
`;
}

/**
 * Generates the convex.config.ts file content
 */
export function generateConfigFile(): string {
	return `// Auto-generated BYOD config v${BYOD_SCHEMA_VERSION}
// DO NOT EDIT - This file is managed by blah.chat

import { defineApp } from "convex/server";

const app = defineApp();

export default app;
`;
}

/**
 * Generates a minimal package.json for the BYOD Convex project
 */
export function generatePackageJson(): string {
	return JSON.stringify(
		{
			name: "blah-chat-byod-instance",
			version: "1.0.0",
			private: true,
			dependencies: {
				convex: "^1.17.0",
			},
		},
		null,
		2,
	);
}

/**
 * Returns all files needed for BYOD deployment
 */
export function generateDeploymentFiles(): Record<string, string> {
	return {
		"convex/schema.ts": generateSchemaFile(),
		"convex.config.ts": generateConfigFile(),
		"package.json": generatePackageJson(),
	};
}
