// BYOD Functions v1
// Auto-generated by blah.chat - DO NOT EDIT

import { query } from "./_generated/server";

// Health check - used to verify connection
export const ping = query({
  args: {},
  handler: async () => {
    return { status: "ok", version: 1, timestamp: Date.now() };
  },
});

// System info - returns schema version
export const getSystemInfo = query({
  args: {},
  handler: async () => {
    return {
      schemaVersion: 1,
      provider: "blah.chat",
      type: "byod",
    };
  },
});
