// Auto-generated BYOD schema v18
// DO NOT EDIT - Generated by scripts/sync-byod-schema.ts

import { defineSchema } from "convex/server";
import { activityEventsTable } from "../../backend/convex/schema/activity";
import {
  bookmarksTable,
  snippetsTable,
} from "../../backend/convex/schema/bookmarks";
import {
  canvasDocumentsTable,
  canvasHistoryTable,
} from "../../backend/convex/schema/canvas";
import {
  conversationParticipantsTable,
  conversationsTable,
  conversationTokenUsageTable,
} from "../../backend/convex/schema/conversations";
import {
  fileChunksTable,
  filesTable,
  knowledgeChunksTable,
  knowledgeSourcesTable,
} from "../../backend/convex/schema/files";
import { memoriesTable } from "../../backend/convex/schema/memories";
import {
  attachmentsTable,
  messagesTable,
  sourceMetadataTable,
  sourcesTable,
  toolCallsTable,
} from "../../backend/convex/schema/messages";
import { notesTable } from "../../backend/convex/schema/notes";
import { notificationsTable } from "../../backend/convex/schema/notifications";
import {
  projectConversationsTable,
  projectFilesTable,
  projectNotesTable,
  projectsTable,
} from "../../backend/convex/schema/projects";
import {
  scheduledPromptsTable,
  sharesTable,
} from "../../backend/convex/schema/shares";
import {
  bookmarkTagsTable,
  noteTagsTable,
  snippetTagsTable,
  tagsTable,
  taskTagsTable,
} from "../../backend/convex/schema/tags";
import { tasksTable } from "../../backend/convex/schema/tasks";
import {
  templatesTable,
  votesTable,
} from "../../backend/convex/schema/templates";
import {
  ttsCacheTable,
  usageRecordsTable,
} from "../../backend/convex/schema/usage";

export default defineSchema({
  conversations: conversationsTable,
  conversationParticipants: conversationParticipantsTable,
  conversationTokenUsage: conversationTokenUsageTable,
  messages: messagesTable,
  attachments: attachmentsTable,
  toolCalls: toolCallsTable,
  sourceMetadata: sourceMetadataTable,
  sources: sourcesTable,
  memories: memoriesTable,
  files: filesTable,
  fileChunks: fileChunksTable,
  knowledgeSources: knowledgeSourcesTable,
  knowledgeChunks: knowledgeChunksTable,
  projects: projectsTable,
  projectConversations: projectConversationsTable,
  projectNotes: projectNotesTable,
  projectFiles: projectFilesTable,
  tasks: tasksTable,
  notes: notesTable,
  bookmarks: bookmarksTable,
  snippets: snippetsTable,
  tags: tagsTable,
  bookmarkTags: bookmarkTagsTable,
  snippetTags: snippetTagsTable,
  noteTags: noteTagsTable,
  taskTags: taskTagsTable,
  shares: sharesTable,
  scheduledPrompts: scheduledPromptsTable,
  usageRecords: usageRecordsTable,
  ttsCache: ttsCacheTable,
  templates: templatesTable,
  votes: votesTable,
  activityEvents: activityEventsTable,
  canvasDocuments: canvasDocumentsTable,
  canvasHistory: canvasHistoryTable,
  notifications: notificationsTable,
});
