// Auto-generated BYOD schema v8
// DO NOT EDIT - Generated by scripts/sync-byod-schema.ts

import { defineSchema } from "convex/server";

import {
  conversationsTable,
  conversationParticipantsTable,
  conversationTokenUsageTable,
} from "../../backend/convex/schema/conversations";

import {
  messagesTable,
  attachmentsTable,
  toolCallsTable,
  sourceMetadataTable,
  sourcesTable,
} from "../../backend/convex/schema/messages";

import {
  memoriesTable,
} from "../../backend/convex/schema/memories";

import {
  filesTable,
  fileChunksTable,
  knowledgeSourcesTable,
  knowledgeChunksTable,
} from "../../backend/convex/schema/files";

import {
  projectsTable,
  projectConversationsTable,
  projectNotesTable,
  projectFilesTable,
} from "../../backend/convex/schema/projects";

import {
  tasksTable,
} from "../../backend/convex/schema/tasks";

import {
  notesTable,
} from "../../backend/convex/schema/notes";

import {
  bookmarksTable,
  snippetsTable,
} from "../../backend/convex/schema/bookmarks";

import {
  tagsTable,
  bookmarkTagsTable,
  snippetTagsTable,
  noteTagsTable,
  taskTagsTable,
} from "../../backend/convex/schema/tags";

import {
  sharesTable,
  scheduledPromptsTable,
} from "../../backend/convex/schema/shares";

import {
  usageRecordsTable,
  ttsCacheTable,
} from "../../backend/convex/schema/usage";

import {
  templatesTable,
  votesTable,
} from "../../backend/convex/schema/templates";

import {
  presentationsTable,
  slidesTable,
  outlineItemsTable,
  designTemplatesTable,
  presentationSessionsTable,
} from "../../backend/convex/schema/presentations";

import {
  activityEventsTable,
} from "../../backend/convex/schema/activity";

import {
  canvasDocumentsTable,
  canvasHistoryTable,
} from "../../backend/convex/schema/canvas";

import {
  notificationsTable,
} from "../../backend/convex/schema/notifications";

export default defineSchema({
  conversations: conversationsTable,
  conversationParticipants: conversationParticipantsTable,
  conversationTokenUsage: conversationTokenUsageTable,
  messages: messagesTable,
  attachments: attachmentsTable,
  toolCalls: toolCallsTable,
  sourceMetadata: sourceMetadataTable,
  sources: sourcesTable,
  memories: memoriesTable,
  files: filesTable,
  fileChunks: fileChunksTable,
  knowledgeSources: knowledgeSourcesTable,
  knowledgeChunks: knowledgeChunksTable,
  projects: projectsTable,
  projectConversations: projectConversationsTable,
  projectNotes: projectNotesTable,
  projectFiles: projectFilesTable,
  tasks: tasksTable,
  notes: notesTable,
  bookmarks: bookmarksTable,
  snippets: snippetsTable,
  tags: tagsTable,
  bookmarkTags: bookmarkTagsTable,
  snippetTags: snippetTagsTable,
  noteTags: noteTagsTable,
  taskTags: taskTagsTable,
  shares: sharesTable,
  scheduledPrompts: scheduledPromptsTable,
  usageRecords: usageRecordsTable,
  ttsCache: ttsCacheTable,
  templates: templatesTable,
  votes: votesTable,
  presentations: presentationsTable,
  slides: slidesTable,
  outlineItems: outlineItemsTable,
  designTemplates: designTemplatesTable,
  presentationSessions: presentationSessionsTable,
  activityEvents: activityEventsTable,
  canvasDocuments: canvasDocumentsTable,
  canvasHistory: canvasHistoryTable,
  notifications: notificationsTable,
});
