/**
 * Composio integration definitions
 *
 * 500+ integrations organized by category for Settings UI
 * Source: https://composio.dev/toolkits (877 total toolkits)
 *
 * Note: Max active integrations is now configurable via Admin Settings.
 * Default is 5, which limits tool count to ~50-100 tools max.
 */

export type IntegrationCategory =
  | "development"
  | "communication"
  | "productivity"
  | "data"
  | "crm"
  | "finance"
  | "automation"
  | "marketing"
  | "design"
  | "ecommerce"
  | "hr"
  | "security"
  | "ai"
  | "entertainment"
  | "education";

export interface IntegrationDefinition {
  id: string;
  name: string;
  description: string;
  category: IntegrationCategory;
  iconUrl?: string;
}

export const INTEGRATION_CATEGORIES: Record<
  IntegrationCategory,
  { label: string; order: number }
> = {
  development: { label: "Development", order: 1 },
  communication: { label: "Communication", order: 2 },
  productivity: { label: "Productivity", order: 3 },
  data: { label: "Data & Analytics", order: 4 },
  crm: { label: "CRM & Sales", order: 5 },
  finance: { label: "Finance", order: 6 },
  automation: { label: "Automation", order: 7 },
  marketing: { label: "Marketing", order: 8 },
  design: { label: "Design", order: 9 },
  ecommerce: { label: "E-commerce", order: 10 },
  hr: { label: "HR & Recruiting", order: 11 },
  security: { label: "Security", order: 12 },
  ai: { label: "AI & ML", order: 13 },
  entertainment: { label: "Entertainment", order: 14 },
  education: { label: "Education", order: 15 },
};

export const INTEGRATIONS: IntegrationDefinition[] = [
  // ==================== DEVELOPMENT ====================
  {
    id: "github",
    name: "GitHub",
    description: "Code hosting, issues, PRs",
    category: "development",
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "DevOps platform",
    category: "development",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    description: "Git repository hosting",
    category: "development",
  },
  {
    id: "linear",
    name: "Linear",
    description: "Issue tracking & planning",
    category: "development",
  },
  {
    id: "jira",
    name: "Jira",
    description: "Project management",
    category: "development",
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Error tracking",
    category: "development",
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "Deployments & hosting",
    category: "development",
  },
  {
    id: "netlify",
    name: "Netlify",
    description: "Web hosting",
    category: "development",
  },
  {
    id: "circleci",
    name: "CircleCI",
    description: "CI/CD pipelines",
    category: "development",
  },
  {
    id: "docker",
    name: "Docker Hub",
    description: "Container registry",
    category: "development",
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Backend platform",
    category: "development",
  },
  {
    id: "neon",
    name: "Neon",
    description: "Serverless Postgres",
    category: "development",
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    description: "Incident management",
    category: "development",
  },
  {
    id: "datadog",
    name: "Datadog",
    description: "Monitoring & analytics",
    category: "development",
  },
  {
    id: "ngrok",
    name: "Ngrok",
    description: "Secure tunnels",
    category: "development",
  },
  {
    id: "contentful",
    name: "Contentful",
    description: "Headless CMS",
    category: "development",
  },
  {
    id: "ably",
    name: "Ably",
    description: "Realtime messaging",
    category: "development",
  },
  {
    id: "baserow",
    name: "Baserow",
    description: "No-code database",
    category: "development",
  },
  {
    id: "gist",
    name: "Gist",
    description: "Code snippets",
    category: "development",
  },
  {
    id: "statuscake",
    name: "StatusCake",
    description: "Uptime monitoring",
    category: "development",
  },
  {
    id: "render",
    name: "Render",
    description: "Cloud hosting",
    category: "development",
  },
  {
    id: "railway",
    name: "Railway",
    description: "App deployment",
    category: "development",
  },
  {
    id: "fly",
    name: "Fly.io",
    description: "App platform",
    category: "development",
  },
  {
    id: "heroku",
    name: "Heroku",
    description: "Cloud platform",
    category: "development",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    description: "Cloud infrastructure",
    category: "development",
  },
  {
    id: "aws",
    name: "AWS",
    description: "Cloud services",
    category: "development",
  },
  {
    id: "gcp",
    name: "Google Cloud",
    description: "Cloud platform",
    category: "development",
  },
  {
    id: "azure",
    name: "Azure",
    description: "Microsoft cloud",
    category: "development",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    description: "CDN & security",
    category: "development",
  },
  {
    id: "postman",
    name: "Postman",
    description: "API development",
    category: "development",
  },
  {
    id: "swagger",
    name: "Swagger",
    description: "API documentation",
    category: "development",
  },
  {
    id: "sonarcloud",
    name: "SonarCloud",
    description: "Code quality",
    category: "development",
  },
  {
    id: "codecov",
    name: "Codecov",
    description: "Code coverage",
    category: "development",
  },
  {
    id: "snyk",
    name: "Snyk",
    description: "Security scanning",
    category: "development",
  },
  {
    id: "launchdarkly",
    name: "LaunchDarkly",
    description: "Feature flags",
    category: "development",
  },
  {
    id: "split",
    name: "Split",
    description: "Feature delivery",
    category: "development",
  },
  {
    id: "terraform",
    name: "Terraform Cloud",
    description: "Infrastructure as code",
    category: "development",
  },
  {
    id: "pulumi",
    name: "Pulumi",
    description: "Infrastructure as code",
    category: "development",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    description: "CI/CD automation",
    category: "development",
  },
  {
    id: "travisci",
    name: "Travis CI",
    description: "CI/CD service",
    category: "development",
  },
  {
    id: "githubactions",
    name: "GitHub Actions",
    description: "CI/CD workflows",
    category: "development",
  },
  {
    id: "gitlabci",
    name: "GitLab CI",
    description: "CI/CD pipelines",
    category: "development",
  },
  {
    id: "shortcut",
    name: "Shortcut",
    description: "Project management",
    category: "development",
  },
  {
    id: "height",
    name: "Height",
    description: "Project management",
    category: "development",
  },
  {
    id: "zeplin",
    name: "Zeplin",
    description: "Design handoff",
    category: "development",
  },

  // ==================== COMMUNICATION ====================
  {
    id: "gmail",
    name: "Gmail",
    description: "Email management",
    category: "communication",
  },
  {
    id: "outlook",
    name: "Outlook",
    description: "Microsoft email",
    category: "communication",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Team messaging",
    category: "communication",
  },
  {
    id: "discord",
    name: "Discord",
    description: "Community chat",
    category: "communication",
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    description: "Enterprise messaging",
    category: "communication",
  },
  {
    id: "telegram",
    name: "Telegram",
    description: "Instant messaging",
    category: "communication",
  },
  {
    id: "whatsappbusiness",
    name: "WhatsApp Business",
    description: "Customer messaging",
    category: "communication",
  },
  {
    id: "intercom",
    name: "Intercom",
    description: "Customer messaging",
    category: "communication",
  },
  {
    id: "zoom",
    name: "Zoom",
    description: "Video conferencing",
    category: "communication",
  },
  {
    id: "googlemeet",
    name: "Google Meet",
    description: "Video meetings",
    category: "communication",
  },
  {
    id: "webex",
    name: "Webex",
    description: "Video conferencing",
    category: "communication",
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "SMS & voice",
    category: "communication",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Email delivery",
    category: "communication",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    description: "Email API",
    category: "communication",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Email marketing",
    category: "communication",
  },
  {
    id: "sendbird",
    name: "Sendbird",
    description: "Chat API",
    category: "communication",
  },
  {
    id: "chatwork",
    name: "Chatwork",
    description: "Business chat",
    category: "communication",
  },
  {
    id: "dialpad",
    name: "Dialpad",
    description: "Business phone",
    category: "communication",
  },
  {
    id: "ringcentral",
    name: "RingCentral",
    description: "Cloud communications",
    category: "communication",
  },
  {
    id: "vonage",
    name: "Vonage",
    description: "Communications API",
    category: "communication",
  },
  {
    id: "telnyx",
    name: "Telnyx",
    description: "Communications platform",
    category: "communication",
  },
  {
    id: "messagebird",
    name: "MessageBird",
    description: "Omnichannel messaging",
    category: "communication",
  },
  {
    id: "crisp",
    name: "Crisp",
    description: "Customer messaging",
    category: "communication",
  },
  {
    id: "drift",
    name: "Drift",
    description: "Conversational marketing",
    category: "communication",
  },
  {
    id: "front",
    name: "Front",
    description: "Team inbox",
    category: "communication",
  },
  {
    id: "helpscout",
    name: "Help Scout",
    description: "Customer support",
    category: "communication",
  },
  {
    id: "liveagent",
    name: "LiveAgent",
    description: "Help desk",
    category: "communication",
  },
  {
    id: "freshchat",
    name: "Freshchat",
    description: "Customer messaging",
    category: "communication",
  },
  {
    id: "zendeskchat",
    name: "Zendesk Chat",
    description: "Live chat",
    category: "communication",
  },
  {
    id: "retellai",
    name: "Retell AI",
    description: "Voice AI",
    category: "communication",
  },
  {
    id: "dailybot",
    name: "DailyBot",
    description: "Team automation",
    category: "communication",
  },
  {
    id: "agentmail",
    name: "Agent Mail",
    description: "Email automation",
    category: "communication",
  },
  {
    id: "stackexchange",
    name: "Stack Exchange",
    description: "Q&A platform",
    category: "communication",
  },

  // ==================== PRODUCTIVITY ====================
  {
    id: "googlecalendar",
    name: "Google Calendar",
    description: "Scheduling & events",
    category: "productivity",
  },
  {
    id: "outlookcalendar",
    name: "Outlook Calendar",
    description: "Microsoft calendar",
    category: "productivity",
  },
  {
    id: "calendly",
    name: "Calendly",
    description: "Scheduling links",
    category: "productivity",
  },
  {
    id: "notion",
    name: "Notion",
    description: "Notes & docs",
    category: "productivity",
  },
  {
    id: "asana",
    name: "Asana",
    description: "Task management",
    category: "productivity",
  },
  {
    id: "trello",
    name: "Trello",
    description: "Kanban boards",
    category: "productivity",
  },
  {
    id: "monday",
    name: "Monday.com",
    description: "Work management",
    category: "productivity",
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "Project management",
    category: "productivity",
  },
  {
    id: "todoist",
    name: "Todoist",
    description: "Personal tasks",
    category: "productivity",
  },
  {
    id: "googledocs",
    name: "Google Docs",
    description: "Documents",
    category: "productivity",
  },
  {
    id: "googlesheets",
    name: "Google Sheets",
    description: "Spreadsheets",
    category: "productivity",
  },
  {
    id: "googleslides",
    name: "Google Slides",
    description: "Presentations",
    category: "productivity",
  },
  {
    id: "googledrive",
    name: "Google Drive",
    description: "File storage",
    category: "productivity",
  },
  {
    id: "googletasks",
    name: "Google Tasks",
    description: "Task management",
    category: "productivity",
  },
  {
    id: "confluence",
    name: "Confluence",
    description: "Team wiki",
    category: "productivity",
  },
  {
    id: "coda",
    name: "Coda",
    description: "Docs & apps",
    category: "productivity",
  },
  {
    id: "wrike",
    name: "Wrike",
    description: "Work management",
    category: "productivity",
  },
  {
    id: "basecamp",
    name: "Basecamp",
    description: "Project management",
    category: "productivity",
  },
  {
    id: "smartsheet",
    name: "Smartsheet",
    description: "Work execution",
    category: "productivity",
  },
  {
    id: "evernote",
    name: "Evernote",
    description: "Note-taking",
    category: "productivity",
  },
  {
    id: "onenote",
    name: "OneNote",
    description: "Microsoft notes",
    category: "productivity",
  },
  {
    id: "bear",
    name: "Bear",
    description: "Markdown notes",
    category: "productivity",
  },
  {
    id: "roam",
    name: "Roam Research",
    description: "Knowledge graph",
    category: "productivity",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    description: "Knowledge base",
    category: "productivity",
  },
  {
    id: "craft",
    name: "Craft",
    description: "Documents",
    category: "productivity",
  },
  {
    id: "dropboxpaper",
    name: "Dropbox Paper",
    description: "Collaborative docs",
    category: "productivity",
  },
  {
    id: "quip",
    name: "Quip",
    description: "Team productivity",
    category: "productivity",
  },
  {
    id: "fibery",
    name: "Fibery",
    description: "Work management",
    category: "productivity",
  },
  {
    id: "canny",
    name: "Canny",
    description: "Feature requests",
    category: "productivity",
  },
  {
    id: "productboard",
    name: "Productboard",
    description: "Product management",
    category: "productivity",
  },
  {
    id: "aha",
    name: "Aha!",
    description: "Product roadmap",
    category: "productivity",
  },
  {
    id: "cal",
    name: "Cal.com",
    description: "Scheduling",
    category: "productivity",
  },
  {
    id: "timely",
    name: "Timely",
    description: "Time tracking",
    category: "productivity",
  },
  {
    id: "harvest",
    name: "Harvest",
    description: "Time tracking",
    category: "productivity",
  },
  {
    id: "toggl",
    name: "Toggl",
    description: "Time tracking",
    category: "productivity",
  },
  {
    id: "clockify",
    name: "Clockify",
    description: "Time tracking",
    category: "productivity",
  },
  {
    id: "ticktick",
    name: "TickTick",
    description: "Task management",
    category: "productivity",
  },
  {
    id: "anydo",
    name: "Any.do",
    description: "Task management",
    category: "productivity",
  },
  {
    id: "things",
    name: "Things",
    description: "Task manager",
    category: "productivity",
  },
  {
    id: "omnifocus",
    name: "OmniFocus",
    description: "Task management",
    category: "productivity",
  },
  {
    id: "habitica",
    name: "Habitica",
    description: "Habit tracking",
    category: "productivity",
  },
  { id: "mem", name: "Mem", description: "AI notes", category: "productivity" },
  {
    id: "rocketlane",
    name: "Rocketlane",
    description: "Client onboarding",
    category: "productivity",
  },
  {
    id: "agiled",
    name: "Agiled",
    description: "Business management",
    category: "productivity",
  },
  {
    id: "onepage",
    name: "OnePage",
    description: "Portfolios",
    category: "productivity",
  },
  {
    id: "linkhut",
    name: "LinkHut",
    description: "Link management",
    category: "productivity",
  },
  {
    id: "pushbullet",
    name: "Pushbullet",
    description: "Cross-device notifications",
    category: "productivity",
  },
  {
    id: "calendarhero",
    name: "CalendarHero",
    description: "Smart scheduling",
    category: "productivity",
  },
  {
    id: "googleadmin",
    name: "Google Admin",
    description: "Workspace admin",
    category: "productivity",
  },

  // ==================== DATA & ANALYTICS ====================
  {
    id: "airtable",
    name: "Airtable",
    description: "Database & spreadsheet",
    category: "data",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    description: "File storage",
    category: "data",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    description: "Microsoft storage",
    category: "data",
  },
  {
    id: "box",
    name: "Box",
    description: "Enterprise storage",
    category: "data",
  },
  {
    id: "mongodb",
    name: "MongoDB Atlas",
    description: "NoSQL database",
    category: "data",
  },
  {
    id: "firebase",
    name: "Firebase",
    description: "App platform",
    category: "data",
  },
  {
    id: "snowflake",
    name: "Snowflake",
    description: "Data warehouse",
    category: "data",
  },
  {
    id: "bigquery",
    name: "BigQuery",
    description: "Data warehouse",
    category: "data",
  },
  {
    id: "redshift",
    name: "Redshift",
    description: "Data warehouse",
    category: "data",
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    description: "Analytics database",
    category: "data",
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    description: "Search & analytics",
    category: "data",
  },
  {
    id: "kibana",
    name: "Kibana",
    description: "Data visualization",
    category: "data",
  },
  {
    id: "googleanalytics",
    name: "Google Analytics",
    description: "Web analytics",
    category: "data",
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Product analytics",
    category: "data",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    description: "Product analytics",
    category: "data",
  },
  {
    id: "posthog",
    name: "PostHog",
    description: "Product analytics",
    category: "data",
  },
  {
    id: "segment",
    name: "Segment",
    description: "Customer data",
    category: "data",
  },
  {
    id: "heap",
    name: "Heap",
    description: "Digital insights",
    category: "data",
  },
  {
    id: "hotjar",
    name: "Hotjar",
    description: "Behavior analytics",
    category: "data",
  },
  {
    id: "fullstory",
    name: "FullStory",
    description: "Digital experience",
    category: "data",
  },
  {
    id: "looker",
    name: "Looker",
    description: "Business intelligence",
    category: "data",
  },
  {
    id: "tableau",
    name: "Tableau",
    description: "Data visualization",
    category: "data",
  },
  {
    id: "powerbi",
    name: "Power BI",
    description: "Business analytics",
    category: "data",
  },
  {
    id: "metabase",
    name: "Metabase",
    description: "Business intelligence",
    category: "data",
  },
  {
    id: "mode",
    name: "Mode",
    description: "Analytics platform",
    category: "data",
  },
  {
    id: "serpapi",
    name: "SerpApi",
    description: "Search results API",
    category: "data",
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    description: "Web crawling",
    category: "data",
  },
  {
    id: "browseai",
    name: "Browse.ai",
    description: "Web scraping",
    category: "data",
  },
  {
    id: "diffbot",
    name: "Diffbot",
    description: "Web data extraction",
    category: "data",
  },
  {
    id: "parsera",
    name: "Parsera",
    description: "Data parsing",
    category: "data",
  },
  {
    id: "peopledatalabs",
    name: "People Data Labs",
    description: "People data",
    category: "data",
  },
  {
    id: "clearbit",
    name: "Clearbit",
    description: "Business data",
    category: "data",
  },
  {
    id: "zoominfo",
    name: "ZoomInfo",
    description: "B2B data",
    category: "data",
  },
  {
    id: "placekey",
    name: "Placekey",
    description: "Location data",
    category: "data",
  },
  {
    id: "foursquare",
    name: "Foursquare",
    description: "Location intelligence",
    category: "data",
  },
  {
    id: "googlemaps",
    name: "Google Maps",
    description: "Maps & places",
    category: "data",
  },
  {
    id: "mapbox",
    name: "Mapbox",
    description: "Maps platform",
    category: "data",
  },
  {
    id: "fireflies",
    name: "Fireflies",
    description: "Meeting transcription",
    category: "data",
  },
  {
    id: "otter",
    name: "Otter.ai",
    description: "Meeting notes",
    category: "data",
  },
  {
    id: "microsoftclarity",
    name: "Microsoft Clarity",
    description: "Behavior analytics",
    category: "data",
  },
  {
    id: "simpleanalytics",
    name: "Simple Analytics",
    description: "Privacy analytics",
    category: "data",
  },
  {
    id: "refiner",
    name: "Refiner",
    description: "Survey analytics",
    category: "data",
  },
  {
    id: "fluxguard",
    name: "Fluxguard",
    description: "Website monitoring",
    category: "data",
  },
  {
    id: "ragic",
    name: "Ragic",
    description: "Database builder",
    category: "data",
  },
  {
    id: "nocodb",
    name: "NocoDB",
    description: "Open source Airtable",
    category: "data",
  },
  {
    id: "seatable",
    name: "SeaTable",
    description: "Online database",
    category: "data",
  },
  {
    id: "googlephotos",
    name: "Google Photos",
    description: "Photo storage",
    category: "data",
  },
  {
    id: "amazons3",
    name: "Amazon S3",
    description: "Object storage",
    category: "data",
  },
  {
    id: "backblaze",
    name: "Backblaze B2",
    description: "Cloud storage",
    category: "data",
  },
  {
    id: "wasabi",
    name: "Wasabi",
    description: "Cloud storage",
    category: "data",
  },

  // ==================== CRM & SALES ====================
  {
    id: "hubspot",
    name: "HubSpot",
    description: "CRM & marketing",
    category: "crm",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Enterprise CRM",
    category: "crm",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "Sales CRM",
    category: "crm",
  },
  {
    id: "zendesk",
    name: "Zendesk",
    description: "Support tickets",
    category: "crm",
  },
  {
    id: "freshdesk",
    name: "Freshdesk",
    description: "Customer support",
    category: "crm",
  },
  {
    id: "apollo",
    name: "Apollo.io",
    description: "Sales intelligence",
    category: "crm",
  },
  { id: "close", name: "Close", description: "Sales CRM", category: "crm" },
  { id: "attio", name: "Attio", description: "CRM platform", category: "crm" },
  {
    id: "zohocrm",
    name: "Zoho CRM",
    description: "CRM software",
    category: "crm",
  },
  {
    id: "zohobigin",
    name: "Zoho Bigin",
    description: "Pipeline CRM",
    category: "crm",
  },
  {
    id: "dynamics365",
    name: "Dynamics 365",
    description: "Microsoft CRM",
    category: "crm",
  },
  { id: "copper", name: "Copper", description: "Google CRM", category: "crm" },
  {
    id: "insightly",
    name: "Insightly",
    description: "CRM & projects",
    category: "crm",
  },
  {
    id: "nutshell",
    name: "Nutshell",
    description: "Sales CRM",
    category: "crm",
  },
  {
    id: "capsule",
    name: "Capsule CRM",
    description: "Simple CRM",
    category: "crm",
  },
  {
    id: "folk",
    name: "Folk",
    description: "Relationship CRM",
    category: "crm",
  },
  {
    id: "affinity",
    name: "Affinity",
    description: "Relationship intelligence",
    category: "crm",
  },
  {
    id: "gorgias",
    name: "Gorgias",
    description: "E-commerce support",
    category: "crm",
  },
  {
    id: "kustomer",
    name: "Kustomer",
    description: "Customer service",
    category: "crm",
  },
  {
    id: "gladly",
    name: "Gladly",
    description: "Customer service",
    category: "crm",
  },
  {
    id: "freshsales",
    name: "Freshsales",
    description: "Sales CRM",
    category: "crm",
  },
  {
    id: "salesmate",
    name: "Salesmate",
    description: "Sales CRM",
    category: "crm",
  },
  { id: "kommo", name: "Kommo", description: "Messenger CRM", category: "crm" },
  {
    id: "nocrm",
    name: "noCRM.io",
    description: "Lead management",
    category: "crm",
  },
  {
    id: "forcemanager",
    name: "ForceManager",
    description: "Mobile CRM",
    category: "crm",
  },
  {
    id: "fireberry",
    name: "Fireberry",
    description: "CRM platform",
    category: "crm",
  },
  { id: "firmao", name: "Firmao", description: "CRM & ERP", category: "crm" },
  {
    id: "simplesat",
    name: "Simplesat",
    description: "Customer feedback",
    category: "crm",
  },
  {
    id: "acculynx",
    name: "AccuLynx",
    description: "Roofing CRM",
    category: "crm",
  },
  {
    id: "agencyzoom",
    name: "AgencyZoom",
    description: "Insurance CRM",
    category: "crm",
  },
  {
    id: "jobnimbus",
    name: "JobNimbus",
    description: "Contractor CRM",
    category: "crm",
  },
  {
    id: "godial",
    name: "GoDial",
    description: "CRM & dialer",
    category: "crm",
  },
  {
    id: "dripjobs",
    name: "Drip Jobs",
    description: "Home services CRM",
    category: "crm",
  },
  {
    id: "bidsketch",
    name: "Bidsketch",
    description: "Proposal software",
    category: "crm",
  },
  {
    id: "qualaroo",
    name: "Qualaroo",
    description: "User feedback",
    category: "crm",
  },

  // ==================== FINANCE ====================
  {
    id: "stripe",
    name: "Stripe",
    description: "Payments",
    category: "finance",
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    description: "Accounting",
    category: "finance",
  },
  { id: "xero", name: "Xero", description: "Accounting", category: "finance" },
  {
    id: "paypal",
    name: "PayPal",
    description: "Payments",
    category: "finance",
  },
  {
    id: "square",
    name: "Square",
    description: "Payments",
    category: "finance",
  },
  {
    id: "brex",
    name: "Brex",
    description: "Corporate cards",
    category: "finance",
  },
  {
    id: "ramp",
    name: "Ramp",
    description: "Expense management",
    category: "finance",
  },
  {
    id: "expensify",
    name: "Expensify",
    description: "Expense reports",
    category: "finance",
  },
  {
    id: "bill",
    name: "Bill.com",
    description: "AP automation",
    category: "finance",
  },
  {
    id: "freshbooks",
    name: "FreshBooks",
    description: "Invoicing",
    category: "finance",
  },
  { id: "wave", name: "Wave", description: "Accounting", category: "finance" },
  {
    id: "zohoinvoice",
    name: "Zoho Invoice",
    description: "Invoicing",
    category: "finance",
  },
  {
    id: "zohobooks",
    name: "Zoho Books",
    description: "Accounting",
    category: "finance",
  },
  {
    id: "sage",
    name: "Sage",
    description: "Business management",
    category: "finance",
  },
  { id: "netsuite", name: "NetSuite", description: "ERP", category: "finance" },
  {
    id: "coinbase",
    name: "Coinbase",
    description: "Crypto exchange",
    category: "finance",
  },
  {
    id: "coinmarketcap",
    name: "CoinMarketCap",
    description: "Crypto data",
    category: "finance",
  },
  {
    id: "coinranking",
    name: "Coinranking",
    description: "Crypto rankings",
    category: "finance",
  },
  {
    id: "tokenmetrics",
    name: "Token Metrics",
    description: "Crypto analytics",
    category: "finance",
  },
  {
    id: "plaid",
    name: "Plaid",
    description: "Financial data",
    category: "finance",
  },
  {
    id: "yodlee",
    name: "Yodlee",
    description: "Financial data",
    category: "finance",
  },
  {
    id: "finicity",
    name: "Finicity",
    description: "Financial data",
    category: "finance",
  },
  {
    id: "chargebee",
    name: "Chargebee",
    description: "Subscription billing",
    category: "finance",
  },
  {
    id: "recurly",
    name: "Recurly",
    description: "Subscription management",
    category: "finance",
  },
  {
    id: "paddle",
    name: "Paddle",
    description: "Payments & tax",
    category: "finance",
  },
  {
    id: "lemonsqueezy",
    name: "Lemon Squeezy",
    description: "Payments for creators",
    category: "finance",
  },
  {
    id: "gumroad",
    name: "Gumroad",
    description: "Creator commerce",
    category: "finance",
  },
  {
    id: "payhip",
    name: "Payhip",
    description: "Digital sales",
    category: "finance",
  },
  {
    id: "giftup",
    name: "Gift Up!",
    description: "Gift cards",
    category: "finance",
  },

  // ==================== AUTOMATION ====================
  {
    id: "zapier",
    name: "Zapier",
    description: "Workflow automation",
    category: "automation",
  },
  {
    id: "make",
    name: "Make",
    description: "Visual automation",
    category: "automation",
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Workflow automation",
    category: "automation",
  },
  {
    id: "pipedream",
    name: "Pipedream",
    description: "Developer workflows",
    category: "automation",
  },
  {
    id: "tray",
    name: "Tray.io",
    description: "Integration platform",
    category: "automation",
  },
  {
    id: "workato",
    name: "Workato",
    description: "Enterprise automation",
    category: "automation",
  },
  {
    id: "powerautomate",
    name: "Power Automate",
    description: "Microsoft automation",
    category: "automation",
  },
  {
    id: "ifttt",
    name: "IFTTT",
    description: "Automation recipes",
    category: "automation",
  },
  {
    id: "activepieces",
    name: "Activepieces",
    description: "Open source automation",
    category: "automation",
  },
  {
    id: "integrately",
    name: "Integrately",
    description: "1-click integrations",
    category: "automation",
  },
  {
    id: "parabola",
    name: "Parabola",
    description: "Data workflows",
    category: "automation",
  },
  {
    id: "automateio",
    name: "Automate.io",
    description: "Cloud integrations",
    category: "automation",
  },
  {
    id: "bannerbear",
    name: "Bannerbear",
    description: "Image automation",
    category: "automation",
  },
  {
    id: "processstreet",
    name: "Process Street",
    description: "Process management",
    category: "automation",
  },
  {
    id: "workiom",
    name: "Workiom",
    description: "Work management",
    category: "automation",
  },
  {
    id: "formsite",
    name: "Formsite",
    description: "Form builder",
    category: "automation",
  },
  {
    id: "servicem8",
    name: "ServiceM8",
    description: "Field service",
    category: "automation",
  },

  // ==================== MARKETING ====================
  {
    id: "twitter",
    name: "Twitter/X",
    description: "Social media",
    category: "marketing",
  },
  {
    id: "facebook",
    name: "Facebook",
    description: "Social media",
    category: "marketing",
  },
  {
    id: "instagram",
    name: "Instagram",
    description: "Photo sharing",
    category: "marketing",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Professional network",
    category: "marketing",
  },
  {
    id: "reddit",
    name: "Reddit",
    description: "Community platform",
    category: "marketing",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    description: "Visual discovery",
    category: "marketing",
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "Short videos",
    category: "marketing",
  },
  {
    id: "buffer",
    name: "Buffer",
    description: "Social scheduling",
    category: "marketing",
  },
  {
    id: "hootsuite",
    name: "Hootsuite",
    description: "Social management",
    category: "marketing",
  },
  {
    id: "sproutsocial",
    name: "Sprout Social",
    description: "Social management",
    category: "marketing",
  },
  {
    id: "later",
    name: "Later",
    description: "Visual planner",
    category: "marketing",
  },
  {
    id: "socialbee",
    name: "SocialBee",
    description: "Social management",
    category: "marketing",
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    description: "Email & SMS marketing",
    category: "marketing",
  },
  {
    id: "convertkit",
    name: "ConvertKit",
    description: "Email for creators",
    category: "marketing",
  },
  {
    id: "drip",
    name: "Drip",
    description: "E-commerce CRM",
    category: "marketing",
  },
  {
    id: "activecampaign",
    name: "ActiveCampaign",
    description: "Email automation",
    category: "marketing",
  },
  {
    id: "constantcontact",
    name: "Constant Contact",
    description: "Email marketing",
    category: "marketing",
  },
  {
    id: "ahrefs",
    name: "Ahrefs",
    description: "SEO tools",
    category: "marketing",
  },
  {
    id: "semrush",
    name: "SEMrush",
    description: "Marketing tools",
    category: "marketing",
  },
  {
    id: "moz",
    name: "Moz",
    description: "SEO software",
    category: "marketing",
  },
  {
    id: "surfer",
    name: "Surfer",
    description: "SEO content",
    category: "marketing",
  },
  {
    id: "neuronwriter",
    name: "NeuronWriter",
    description: "SEO writing",
    category: "marketing",
  },
  {
    id: "brandfetch",
    name: "Brandfetch",
    description: "Brand assets",
    category: "marketing",
  },
  {
    id: "crustdata",
    name: "CrustData",
    description: "B2B data",
    category: "marketing",
  },
  {
    id: "eventbrite",
    name: "Eventbrite",
    description: "Event management",
    category: "marketing",
  },
  {
    id: "luma",
    name: "Luma",
    description: "Event hosting",
    category: "marketing",
  },
  {
    id: "deadlinefunnel",
    name: "Deadline Funnel",
    description: "Urgency marketing",
    category: "marketing",
  },
  {
    id: "amcards",
    name: "AMCards",
    description: "Card campaigns",
    category: "marketing",
  },
  {
    id: "typefully",
    name: "Typefully",
    description: "Twitter scheduling",
    category: "marketing",
  },
  {
    id: "l2s",
    name: "L2S",
    description: "Lead generation",
    category: "marketing",
  },

  // ==================== DESIGN ====================
  {
    id: "figma",
    name: "Figma",
    description: "Design tool",
    category: "design",
  },
  { id: "miro", name: "Miro", description: "Whiteboard", category: "design" },
  {
    id: "canva",
    name: "Canva",
    description: "Graphic design",
    category: "design",
  },
  {
    id: "webflow",
    name: "Webflow",
    description: "Web design",
    category: "design",
  },
  {
    id: "mural",
    name: "Mural",
    description: "Visual collaboration",
    category: "design",
  },
  {
    id: "sketch",
    name: "Sketch",
    description: "Design tool",
    category: "design",
  },
  {
    id: "adobexd",
    name: "Adobe XD",
    description: "UI/UX design",
    category: "design",
  },
  {
    id: "invision",
    name: "InVision",
    description: "Design platform",
    category: "design",
  },
  {
    id: "framer",
    name: "Framer",
    description: "Web builder",
    category: "design",
  },
  {
    id: "principle",
    name: "Principle",
    description: "Animation design",
    category: "design",
  },
  {
    id: "lottie",
    name: "Lottie",
    description: "Animation library",
    category: "design",
  },
  {
    id: "rive",
    name: "Rive",
    description: "Interactive design",
    category: "design",
  },
  {
    id: "spline",
    name: "Spline",
    description: "3D design",
    category: "design",
  },
  {
    id: "blender",
    name: "Blender",
    description: "3D creation",
    category: "design",
  },
  {
    id: "htmltoimage",
    name: "HTML to Image",
    description: "Screenshot API",
    category: "design",
  },
  {
    id: "abyssale",
    name: "Abyssale",
    description: "Image automation",
    category: "design",
  },
  {
    id: "alttextai",
    name: "Alttext AI",
    description: "Alt text generation",
    category: "design",
  },
  {
    id: "removebg",
    name: "Remove.bg",
    description: "Background removal",
    category: "design",
  },
  {
    id: "photoroom",
    name: "PhotoRoom",
    description: "Photo editing",
    category: "design",
  },
  {
    id: "placeholder",
    name: "Placeholder",
    description: "Placeholder images",
    category: "design",
  },
  {
    id: "unsplash",
    name: "Unsplash",
    description: "Stock photos",
    category: "design",
  },
  {
    id: "pexels",
    name: "Pexels",
    description: "Stock media",
    category: "design",
  },

  // ==================== E-COMMERCE ====================
  {
    id: "shopify",
    name: "Shopify",
    description: "E-commerce platform",
    category: "ecommerce",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    description: "WordPress e-commerce",
    category: "ecommerce",
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    description: "E-commerce platform",
    category: "ecommerce",
  },
  {
    id: "magento",
    name: "Magento",
    description: "E-commerce platform",
    category: "ecommerce",
  },
  {
    id: "squarespace",
    name: "Squarespace",
    description: "Website builder",
    category: "ecommerce",
  },
  {
    id: "wix",
    name: "Wix",
    description: "Website builder",
    category: "ecommerce",
  },
  {
    id: "amazonseller",
    name: "Amazon Seller",
    description: "Marketplace",
    category: "ecommerce",
  },
  {
    id: "ebay",
    name: "eBay",
    description: "Marketplace",
    category: "ecommerce",
  },
  {
    id: "etsy",
    name: "Etsy",
    description: "Handmade marketplace",
    category: "ecommerce",
  },
  {
    id: "printful",
    name: "Printful",
    description: "Print on demand",
    category: "ecommerce",
  },
  {
    id: "printify",
    name: "Printify",
    description: "Print on demand",
    category: "ecommerce",
  },
  {
    id: "oberlo",
    name: "Oberlo",
    description: "Dropshipping",
    category: "ecommerce",
  },
  {
    id: "junglescout",
    name: "Jungle Scout",
    description: "Amazon research",
    category: "ecommerce",
  },
  {
    id: "asindata",
    name: "ASIN Data API",
    description: "Amazon data",
    category: "ecommerce",
  },
  {
    id: "baselinker",
    name: "BaseLinker",
    description: "E-commerce automation",
    category: "ecommerce",
  },
  {
    id: "cloudcart",
    name: "CloudCart",
    description: "E-commerce platform",
    category: "ecommerce",
  },
  {
    id: "memberstack",
    name: "Memberstack",
    description: "Memberships",
    category: "ecommerce",
  },
  {
    id: "addresszen",
    name: "Addresszen",
    description: "Address validation",
    category: "ecommerce",
  },
  {
    id: "countdownapi",
    name: "Countdown API",
    description: "Timer widgets",
    category: "ecommerce",
  },
  {
    id: "recharge",
    name: "Recharge",
    description: "Subscriptions",
    category: "ecommerce",
  },
  {
    id: "bold",
    name: "Bold",
    description: "Shopify apps",
    category: "ecommerce",
  },
  {
    id: "yotpo",
    name: "Yotpo",
    description: "Reviews & UGC",
    category: "ecommerce",
  },
  {
    id: "stamped",
    name: "Stamped",
    description: "Reviews",
    category: "ecommerce",
  },
  {
    id: "klaviyoecomm",
    name: "Klaviyo",
    description: "E-commerce marketing",
    category: "ecommerce",
  },
  {
    id: "shipstation",
    name: "ShipStation",
    description: "Shipping",
    category: "ecommerce",
  },
  {
    id: "shippo",
    name: "Shippo",
    description: "Shipping API",
    category: "ecommerce",
  },
  {
    id: "easypost",
    name: "EasyPost",
    description: "Shipping API",
    category: "ecommerce",
  },

  // ==================== HR & RECRUITING ====================
  { id: "lever", name: "Lever", description: "Recruiting", category: "hr" },
  { id: "ashby", name: "Ashby", description: "ATS", category: "hr" },
  {
    id: "greenhouse",
    name: "Greenhouse",
    description: "Recruiting",
    category: "hr",
  },
  {
    id: "workday",
    name: "Workday",
    description: "HR management",
    category: "hr",
  },
  {
    id: "bamboohr",
    name: "BambooHR",
    description: "HR software",
    category: "hr",
  },
  { id: "gusto", name: "Gusto", description: "Payroll & HR", category: "hr" },
  {
    id: "rippling",
    name: "Rippling",
    description: "HR platform",
    category: "hr",
  },
  { id: "deel", name: "Deel", description: "Global payroll", category: "hr" },
  { id: "remote", name: "Remote", description: "Global HR", category: "hr" },
  {
    id: "oyster",
    name: "Oyster",
    description: "Global employment",
    category: "hr",
  },
  {
    id: "lattice",
    name: "Lattice",
    description: "Performance",
    category: "hr",
  },
  { id: "15five", name: "15Five", description: "Performance", category: "hr" },
  {
    id: "cultureamp",
    name: "Culture Amp",
    description: "Employee experience",
    category: "hr",
  },
  {
    id: "workable",
    name: "Workable",
    description: "Recruiting",
    category: "hr",
  },
  { id: "jazz", name: "JazzHR", description: "Recruiting", category: "hr" },
  {
    id: "breezy",
    name: "Breezy HR",
    description: "Recruiting",
    category: "hr",
  },
  { id: "recruitee", name: "Recruitee", description: "ATS", category: "hr" },
  {
    id: "personio",
    name: "Personio",
    description: "HR software",
    category: "hr",
  },
  {
    id: "factorial",
    name: "Factorial",
    description: "HR software",
    category: "hr",
  },
  { id: "hibob", name: "HiBob", description: "HR platform", category: "hr" },
  { id: "namely", name: "Namely", description: "HR software", category: "hr" },
  {
    id: "zenefits",
    name: "Zenefits",
    description: "HR platform",
    category: "hr",
  },
  {
    id: "justworks",
    name: "Justworks",
    description: "HR & payroll",
    category: "hr",
  },
  { id: "paychex", name: "Paychex", description: "Payroll", category: "hr" },
  { id: "adp", name: "ADP", description: "Payroll & HR", category: "hr" },

  // ==================== SECURITY ====================
  {
    id: "okta",
    name: "Okta",
    description: "Identity management",
    category: "security",
  },
  {
    id: "auth0",
    name: "Auth0",
    description: "Authentication",
    category: "security",
  },
  {
    id: "onelogin",
    name: "OneLogin",
    description: "Identity management",
    category: "security",
  },
  { id: "duo", name: "Duo Security", description: "MFA", category: "security" },
  {
    id: "1password",
    name: "1Password",
    description: "Password manager",
    category: "security",
  },
  {
    id: "lastpass",
    name: "LastPass",
    description: "Password manager",
    category: "security",
  },
  {
    id: "dashlane",
    name: "Dashlane",
    description: "Password manager",
    category: "security",
  },
  {
    id: "keeper",
    name: "Keeper",
    description: "Password manager",
    category: "security",
  },
  {
    id: "bitwarden",
    name: "Bitwarden",
    description: "Password manager",
    category: "security",
  },
  {
    id: "crowdstrike",
    name: "CrowdStrike",
    description: "Endpoint security",
    category: "security",
  },
  {
    id: "sentinelone",
    name: "SentinelOne",
    description: "Endpoint security",
    category: "security",
  },
  {
    id: "jamf",
    name: "Jamf",
    description: "Apple management",
    category: "security",
  },
  {
    id: "kandji",
    name: "Kandji",
    description: "Apple MDM",
    category: "security",
  },
  {
    id: "mosyle",
    name: "Mosyle",
    description: "Apple management",
    category: "security",
  },
  {
    id: "drata",
    name: "Drata",
    description: "Compliance",
    category: "security",
  },
  {
    id: "vanta",
    name: "Vanta",
    description: "Compliance",
    category: "security",
  },
  {
    id: "secureframe",
    name: "Secureframe",
    description: "Compliance",
    category: "security",
  },
  {
    id: "borneo",
    name: "Borneo",
    description: "Data security",
    category: "security",
  },
  {
    id: "hashicorpvault",
    name: "HashiCorp Vault",
    description: "Secrets management",
    category: "security",
  },
  {
    id: "doppler",
    name: "Doppler",
    description: "Secrets management",
    category: "security",
  },

  // ==================== AI & ML ====================
  { id: "openai", name: "OpenAI", description: "AI platform", category: "ai" },
  {
    id: "anthropic",
    name: "Anthropic",
    description: "AI safety",
    category: "ai",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "ML platform",
    category: "ai",
  },
  {
    id: "replicate",
    name: "Replicate",
    description: "ML models",
    category: "ai",
  },
  {
    id: "stability",
    name: "Stability AI",
    description: "Image generation",
    category: "ai",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    description: "Image generation",
    category: "ai",
  },
  { id: "runway", name: "Runway", description: "AI video", category: "ai" },
  { id: "heygen", name: "HeyGen", description: "AI video", category: "ai" },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "Voice AI",
    category: "ai",
  },
  {
    id: "whisper",
    name: "Whisper",
    description: "Speech recognition",
    category: "ai",
  },
  {
    id: "deepgram",
    name: "Deepgram",
    description: "Speech AI",
    category: "ai",
  },
  {
    id: "assemblyai",
    name: "AssemblyAI",
    description: "Speech AI",
    category: "ai",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "AI search",
    category: "ai",
  },
  { id: "tavily", name: "Tavily", description: "AI search", category: "ai" },
  { id: "exa", name: "Exa", description: "AI search", category: "ai" },
  {
    id: "yousearch",
    name: "You.com",
    description: "AI search",
    category: "ai",
  },
  {
    id: "codeinterpreter",
    name: "Code Interpreter",
    description: "Code execution",
    category: "ai",
  },
  {
    id: "griptape",
    name: "Griptape",
    description: "AI framework",
    category: "ai",
  },
  {
    id: "langchain",
    name: "LangChain",
    description: "LLM framework",
    category: "ai",
  },
  {
    id: "llamaindex",
    name: "LlamaIndex",
    description: "Data framework",
    category: "ai",
  },
  {
    id: "pinecone",
    name: "Pinecone",
    description: "Vector database",
    category: "ai",
  },
  {
    id: "weaviate",
    name: "Weaviate",
    description: "Vector database",
    category: "ai",
  },
  {
    id: "qdrant",
    name: "Qdrant",
    description: "Vector database",
    category: "ai",
  },
  {
    id: "chroma",
    name: "Chroma",
    description: "Vector database",
    category: "ai",
  },
  { id: "mem0", name: "Mem0", description: "Memory layer", category: "ai" },
  {
    id: "semanticscholar",
    name: "Semantic Scholar",
    description: "Research AI",
    category: "ai",
  },
  { id: "lmnt", name: "LMNT", description: "Voice AI", category: "ai" },
  {
    id: "humanloop",
    name: "Humanloop",
    description: "LLM evaluation",
    category: "ai",
  },
  {
    id: "textrazor",
    name: "TextRazor",
    description: "Text analysis",
    category: "ai",
  },
  { id: "bolna", name: "Bolna", description: "Voice AI", category: "ai" },
  {
    id: "gong",
    name: "Gong",
    description: "Revenue intelligence",
    category: "ai",
  },
  {
    id: "recallai",
    name: "Recall AI",
    description: "Meeting AI",
    category: "ai",
  },
  {
    id: "zenrows",
    name: "ZenRows",
    description: "Web scraping API",
    category: "ai",
  },

  // ==================== ENTERTAINMENT ====================
  {
    id: "youtube",
    name: "YouTube",
    description: "Video platform",
    category: "entertainment",
  },
  {
    id: "spotify",
    name: "Spotify",
    description: "Music streaming",
    category: "entertainment",
  },
  {
    id: "twitch",
    name: "Twitch",
    description: "Live streaming",
    category: "entertainment",
  },
  {
    id: "vimeo",
    name: "Vimeo",
    description: "Video hosting",
    category: "entertainment",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    description: "Audio platform",
    category: "entertainment",
  },
  {
    id: "applemusic",
    name: "Apple Music",
    description: "Music streaming",
    category: "entertainment",
  },
  {
    id: "deezer",
    name: "Deezer",
    description: "Music streaming",
    category: "entertainment",
  },
  {
    id: "bandcamp",
    name: "Bandcamp",
    description: "Music platform",
    category: "entertainment",
  },
  {
    id: "mux",
    name: "Mux",
    description: "Video infrastructure",
    category: "entertainment",
  },
  {
    id: "cloudinary",
    name: "Cloudinary",
    description: "Media management",
    category: "entertainment",
  },
  {
    id: "bunny",
    name: "Bunny.net",
    description: "CDN & streaming",
    category: "entertainment",
  },

  // ==================== EDUCATION ====================
  {
    id: "canvaslms",
    name: "Canvas",
    description: "Learning management",
    category: "education",
  },
  {
    id: "d2l",
    name: "D2L Brightspace",
    description: "Learning platform",
    category: "education",
  },
  {
    id: "moodle",
    name: "Moodle",
    description: "Learning platform",
    category: "education",
  },
  {
    id: "blackboard",
    name: "Blackboard",
    description: "Learning management",
    category: "education",
  },
  {
    id: "schoology",
    name: "Schoology",
    description: "Learning management",
    category: "education",
  },
  {
    id: "googleclassroom",
    name: "Google Classroom",
    description: "Education platform",
    category: "education",
  },
  {
    id: "teachable",
    name: "Teachable",
    description: "Course creation",
    category: "education",
  },
  {
    id: "thinkific",
    name: "Thinkific",
    description: "Course creation",
    category: "education",
  },
  {
    id: "kajabi",
    name: "Kajabi",
    description: "Knowledge business",
    category: "education",
  },
  {
    id: "podia",
    name: "Podia",
    description: "Digital products",
    category: "education",
  },
  {
    id: "skillshare",
    name: "Skillshare",
    description: "Learning community",
    category: "education",
  },
  {
    id: "udemy",
    name: "Udemy",
    description: "Online courses",
    category: "education",
  },
  {
    id: "coursera",
    name: "Coursera",
    description: "Online learning",
    category: "education",
  },
  {
    id: "coassemble",
    name: "Coassemble",
    description: "Training platform",
    category: "education",
  },
  {
    id: "learnworlds",
    name: "LearnWorlds",
    description: "Course platform",
    category: "education",
  },
];

export const INTEGRATIONS_BY_ID = new Map(INTEGRATIONS.map((i) => [i.id, i]));

export const INTEGRATIONS_BY_CATEGORY = INTEGRATIONS.reduce(
  (acc, integration) => {
    if (!acc[integration.category]) {
      acc[integration.category] = [];
    }
    acc[integration.category].push(integration);
    return acc;
  },
  {} as Record<IntegrationCategory, IntegrationDefinition[]>,
);
